from __future__ import annotations

from datetime import date, timedelta

import pandas as pd


def build_demo_customers(today: date | None = None) -> pd.DataFrame:
    """Return a small, date-aware portfolio for the public Lite demo."""
    today = today or date.today()

    def days_ago(days: int) -> date:
        return today - timedelta(days=days)

    def days_from_now(days: int) -> date:
        return today + timedelta(days=days)

    records = [
        {
            "customer_id": "DEMO-001",
            "customer_name": "Aurora Digital",
            "owner": "Marina",
            "last_contact_date": days_ago(2),
            "next_contact_date": today,
            "contact_status": "Waiting",
            "response_status": "Waiting",
            "follow_up_count": 1,
            "renewal_days": 18,
            "notes": "Cliente demonstrativo com boa adoção.",
            "entry_date": days_ago(150),
            "plan_cycle": "Mensal",
            "customer_status": "Active",
            "cancellation_date": None,
            "cancellation_reason": None,
            "is_internal": False,
            "payment_platform": "Stripe",
            "account_count": 2,
            "last_platform_activity_date": days_ago(1),
            "platform_status": "Healthy",
        },
        {
            "customer_id": "DEMO-002",
            "customer_name": "Nexo Consultoria",
            "owner": "Álvaro",
            "last_contact_date": days_ago(12),
            "next_contact_date": days_ago(2),
            "contact_status": "Follow-up due",
            "response_status": "No response",
            "follow_up_count": 2,
            "renewal_days": 26,
            "notes": "Requer acompanhamento de adoção.",
            "entry_date": days_ago(95),
            "plan_cycle": "Trimestral",
            "customer_status": "Active",
            "cancellation_date": None,
            "cancellation_reason": None,
            "is_internal": False,
            "payment_platform": "Iugu",
            "account_count": 1,
            "last_platform_activity_date": days_ago(12),
            "platform_status": "AtRisk",
        },
        {
            "customer_id": "DEMO-003",
            "customer_name": "Vértice Labs",
            "owner": "Marina",
            "last_contact_date": days_ago(38),
            "next_contact_date": days_ago(7),
            "contact_status": "Follow-up due",
            "response_status": "Ghosted",
            "follow_up_count": 4,
            "renewal_days": 9,
            "notes": "Sem retorno nas últimas tentativas.",
            "entry_date": days_ago(210),
            "plan_cycle": "Semestral",
            "customer_status": "Active",
            "cancellation_date": None,
            "cancellation_reason": None,
            "is_internal": False,
            "payment_platform": "Pagar.me",
            "account_count": 3,
            "last_platform_activity_date": days_ago(34),
            "platform_status": "Dormant",
        },
        {
            "customer_id": "DEMO-004",
            "customer_name": "Estúdio Horizonte",
            "owner": "Álvaro",
            "last_contact_date": None,
            "next_contact_date": days_from_now(1),
            "contact_status": "Not contacted",
            "response_status": "Not applicable",
            "follow_up_count": 0,
            "renewal_days": 42,
            "notes": "Onboarding recém-iniciado.",
            "entry_date": days_ago(8),
            "plan_cycle": "Mensal",
            "customer_status": "Active",
            "cancellation_date": None,
            "cancellation_reason": None,
            "is_internal": False,
            "payment_platform": "Asaas",
            "account_count": 1,
            "last_platform_activity_date": None,
            "platform_status": "NeverActivated",
        },
        {
            "customer_id": "DEMO-005",
            "customer_name": "Orbe Tecnologia",
            "owner": "Marina",
            "last_contact_date": days_ago(20),
            "next_contact_date": None,
            "contact_status": "Contacted",
            "response_status": "Responded",
            "follow_up_count": 1,
            "renewal_days": None,
            "notes": "Registro histórico para análise de churn.",
            "entry_date": days_ago(280),
            "plan_cycle": "Mensal",
            "customer_status": "Cancelled",
            "cancellation_date": days_ago(18),
            "cancellation_reason": "Reestruturação de orçamento",
            "is_internal": False,
            "payment_platform": "Stripe",
            "account_count": 1,
            "last_platform_activity_date": days_ago(40),
            "platform_status": "Dormant",
        },
        {
            "customer_id": "DEMO-006",
            "customer_name": "Lume Partners",
            "owner": "Álvaro",
            "last_contact_date": days_ago(15),
            "next_contact_date": None,
            "contact_status": "Contacted",
            "response_status": "Responded",
            "follow_up_count": 1,
            "renewal_days": None,
            "notes": "Registro histórico de desistência.",
            "entry_date": days_ago(55),
            "plan_cycle": "Trimestral",
            "customer_status": "Desistencia",
            "cancellation_date": days_ago(6),
            "cancellation_reason": "Desistência durante implantação",
            "is_internal": False,
            "payment_platform": "Iugu",
            "account_count": 1,
            "last_platform_activity_date": days_ago(22),
            "platform_status": "Dormant",
        },
    ]
    return pd.DataFrame(records)
